### ISSUE TITLE
product.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [IvanKhud/learn-angular#3]
export class Product {
    constructor(
        public name: string,
        public description: string,
        public price: number,
        public category: Category,
        public isAvailable: boolean,
    ) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.category = category;
        this.isAvailable = isAvailable;
    }
}
Если вы используете модификатор доступа для параметров конструктора, то не нужно ничего в теле конструктора присваивать. Это происходит автоматически.

**Comment by IvanKhud** [comment]
убрал лишние строчки.
